clc
nruns=5;
A=[];
B=[];
C=[];
D=[];
E=[];
F=[];
for l=1:nruns
fix_the_model=320;
ninput=12;
k1=0.13;
k2=0.02;
k3=0.002;
parameters(1)=k1;
parameters(2)=k2;
parameters(3)=k3;
subset=8;
mode='p';
%[centers, parameter, output,Tetak,cik] = eTS(Data,r,fix_the_model,'p');
[Center_upper,Center_lower,Spread_multivariate,sigmapoints,Tetak,time,rule,input,design_factor,y,dilation,translation,recurrent_link,recurrent_link1,count_samples,nrmse_fix,rmse_fix,ndei_fix,traceinputweight] = pRVFLN(cutter, fix_the_model,parameters,ninput,subset,mode);
nparameters=(2*subset+1)*rule(end);
A(l)=rmse_fix;
B(l)=size(Center_upper,1);
C(l)=time;
D(l)=nparameters;
E(l)=count_samples;
end
Arat=mean((A));
Adev=std((A));
Brat=mean((B));
Bstd=std((B));
Crat=mean((C));
Cdev=std((C));
Drat=mean((D));
Ddev=std((D));
Erat=mean((E));
Edev=std((E));